refactor: Refactor output types
DaveSkender/Stock.Indicators.Python pull request #91
Opened 2022-01-01 08:02 UTC by LeeDongGeon1996

### Description

 - Refactor output types to fit to dll.

### Checklist

- [ ] My code follows the existing style, code structure, and naming taxonomy
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code and included any verifying manual calculations
- [ ] I have added or updated unit tests that prove my fix is effective or that my feature works, and achieves sufficient code coverage.  New and existing unit tests pass locally and in the build (below) with my changes
- [ ] My changes generate no new warnings and running code analysis does not produce any issues
- [ ] I have added or run the performance tests that depict optimal execution times
- [ ] I have made corresponding changes to the documentation

2022-01-01 09:27 UTC, DaveSkender requested changes

2022-01-01 09:27 UTC, DaveSkender commented on stock_indicators/indicators/chandelier.py
> +    def chandelier_exit(self) -> Optional[Decimal]:
Not sure if it's here or in one of the other Chandelier data types.  You'll have to add the latest v1.20.2 to see which is broken in your local version.  The production build uses the latest DLL.

2022-01-02 10:57 UTC, DaveSkender approved these changes

2022-01-03 05:52 UTC, LeeDongGeon1996 commented
@DaveSkender  Thanks 👍

2022-01-03 05:52 UTC, merged